In [63]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [64]:
#import dataset
train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')
X = train_data.iloc[:,:-1].values
y = train_data.iloc[:,562].values
X_test = test_data.iloc[:,:-1].values
y_test = test_data.iloc[:,562].values


In [65]:
print(train_data)

      tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0              0.288585          -0.020294          -0.132905   
1              0.278419          -0.016411          -0.123520   
2              0.279653          -0.019467          -0.113462   
3              0.279174          -0.026201          -0.123283   
4              0.276629          -0.016570          -0.115362   
5              0.277199          -0.010098          -0.105137   
6              0.279454          -0.019641          -0.110022   
7              0.277432          -0.030488          -0.125360   
8              0.277293          -0.021751          -0.120751   
9              0.280586          -0.009960          -0.106065   
10             0.276880          -0.012722          -0.103438   
11             0.276228          -0.021441          -0.108202   
12             0.278457          -0.020415          -0.112732   
13             0.277175          -0.014713          -0.106756   
14             0.297946  

In [66]:
print(test_data)

      tBodyAcc-mean()-X  tBodyAcc-mean()-Y  tBodyAcc-mean()-Z  \
0              0.257178          -0.023285          -0.014654   
1              0.286027          -0.013163          -0.119083   
2              0.275485          -0.026050          -0.118152   
3              0.270298          -0.032614          -0.117520   
4              0.274833          -0.027848          -0.129527   
5              0.279220          -0.018620          -0.113902   
6              0.279746          -0.018271          -0.104000   
7              0.274601          -0.025035          -0.116831   
8              0.272529          -0.020954          -0.114472   
9              0.275746          -0.010372          -0.099776   
10             0.278596          -0.015232          -0.098908   
11             0.279152          -0.021879          -0.109731   
12             0.274544          -0.023145          -0.112540   
13             0.269066          -0.027686          -0.110178   
14             0.275579  

In [67]:
# Encoding the train_data
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

# Encoding the test_data
from sklearn.preprocessing import LabelEncoder
labelencoder_y_test = LabelEncoder()
y_test = labelencoder_y_test.fit_transform(y_test)

In [68]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [69]:
y_pred= classifier.predict(X_test)
print(y_pred)

[2 2 2 ... 5 5 5]


In [70]:
print(y_test)

[2 2 2 ... 5 5 5]


In [71]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[511  19   7   0   0   0]
 [  0 332 157   0   0   2]
 [  0  66 465   1   0   0]
 [  0   0   0 423  43  30]
 [  0   0   0  78 313  29]
 [  0   0   0 101  28 342]]


In [72]:
print(accuracy_score(y_test, y_pred))

0.8096369189005769
